frontend:
  image:
    repository: acrclustersage.azurecr.io/clustersage/frontend
    tag: 62f5bae
serviceAccount:
  annotations:
    azure.workload.identity/client-id: "89aa8bbd-863c-4c73-ad50-2735df059f9f"
podLabels:
  azure.workload.identity/use: "true"
keyVault:
  enabled: true
  vaultName: kvclustersageprod
  tenantId: e273e7a6-0676-4113-8575-ca2b6f3dd2ad
  clientId: 89aa8bbd-863c-4c73-ad50-2735df059f9f
  objects:
    - name: database-url
      alias: DATABASE_URL
    - name: jwt-secret
      alias: JWT_SECRET
    - name: agent-token-secret
      alias: AGENT_TOKEN_SECRET
    - name: azure-storage-connection-string
      alias: AZURE_STORAGE_CONNECTION_STRING
backend:
  image:
    repository: acrclustersage.azurecr.io/clustersage/backend
    tag: a6832e3
  env:
    APP_ENV: prod
    PUBLIC_APP_URL: https://nexaflow.site
    PUBLIC_API_URL: https://nexaflow.site
    CORS_ALLOWED_ORIGINS: https://nexaflow.site,https://www.nexaflow.site
    AZURE_AI_FOUNDRY_ENDPOINT: https://oaiclustersageprod.openai.azure.com/
    AZURE_AI_FOUNDRY_PROJECT_NAME: ""
    AZURE_AI_FOUNDRY_PROJECT_ID: ""
    AZURE_AI_FOUNDRY_DEPLOYMENT_NAME: gpt-4.1-mini
    AZURE_AI_FOUNDRY_API_VERSION: 2024-05-01-preview
    AZURE_CLIENT_ID: 89aa8bbd-863c-4c73-ad50-2735df059f9f
    AI_ANALYSIS_ENABLED: "true"
    AI_CLUSTER_QUERY_ENABLED: "true"
    ALERT_EVALUATION_ENABLED: "true"
    ALERT_EVALUATION_INTERVAL_SECONDS: "60"
    REMEDIATION_APPROVAL_ENABLED: "true"
    AGENT_REMEDIATION_ENABLED: "false"
    AI_MAX_LOG_LINES_PER_ANALYSIS: "200"
    AI_MAX_TOKENS: "1200"
    AI_TEMPERATURE: "0"
    AI_PROMPT_VERSION: v1
    AZURE_STORAGE_CONTAINER: clustersage-data
    AZURE_SERVICEBUS_FULLY_QUALIFIED_NAMESPACE: sb-clustersage-prod.servicebus.windows.net
    CLUSTER_CONNECTED_QUEUE_NAME: cluster-connected
    AZURE_COMMUNICATION_EMAIL_ENDPOINT: https://acs-clustersage-prod.unitedstates.communication.azure.com
    EMAIL_SENDER_ADDRESS: donotreply@70b96c04-4b2f-402c-8e1e-724eb14fb782.azurecomm.net
emailWorker:
  image:
    repository: acrclustersage.azurecr.io/clustersage/email-worker
    tag: 0994a0c
migrationJob:
  image:
    repository: acrclustersage.azurecr.io/clustersage/backend
    tag: a6832e3
gateway:
  hostname: nexaflow.site
  hostnames:
    - nexaflow.site
    - www.nexaflow.site
