frontend:
  image:
    repository: acrclustersage.azurecr.io/clustersage/frontend
    tag: dcff03f
    digest: "sha256:b19a7474088739df55fdb024a3f3aadbb3d25904b6b022146754db5b5a7608f0"
backend:
  image:
    repository: acrclustersage.azurecr.io/clustersage/backend
    tag: staging-placeholder
    digest: ""
emailWorker:
  image:
    repository: acrclustersage.azurecr.io/clustersage/email-worker
    tag: staging-placeholder
    digest: ""
migrationJob:
  image:
    repository: acrclustersage.azurecr.io/clustersage/backend
    tag: staging-placeholder
    digest: ""
gateway:
  hostname: staging.nexaflow.site
  hostnames:
    - staging.nexaflow.site
