apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clustersage-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: clustersage
  sources:
    - repoURL: https://github.com/ClusterSage/ClusterSage-helm.git
      targetRevision: main
      path: charts/clustersage
      helm:
        valueFiles:
          - values-dev.yaml
          - $values/environments/dev/values/clustersage-values.yaml
    - repoURL: https://github.com/ClusterSage/ClusterSage-gitops.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
