frontend:
  image:
    repository: acrclustersage.azurecr.io/clustersage/frontend
    tag: 582f1e7
    digest: sha256:afed9155e57067b2121533f3280bdaa91e54dc9260c3070947f0200ea46e98d8
backend:
  image:
    repository: acrclustersage.azurecr.io/clustersage/backend
    tag: 46fa086
    digest: sha256:3dbd8952a83495ea2dd98f5e9f5b918d7015f5b216f8a91077393e91846db641
emailWorker:
  image:
    repository: acrclustersage.azurecr.io/clustersage/email-worker
    tag: 46fa086
    digest: sha256:b02e49f4e8118ece0a6ba3b3a80b3c1cffd4b6ee24321436e829dcc07f401132
gateway:
  hostname: dev.nexaflow.site
  hostnames:
    - dev.nexaflow.site
migrationJob:
  image:
    repository: acrclustersage.azurecr.io/clustersage/backend
    tag: 46fa086
    digest: sha256:3dbd8952a83495ea2dd98f5e9f5b918d7015f5b216f8a91077393e91846db641
