frontend:
  image:
    repository: acrclustersage.azurecr.io/clustersage/frontend
    tag: dev-placeholder
backend:
  image:
    repository: acrclustersage.azurecr.io/clustersage/backend
    tag: b4766ce
    digest: sha256:53895ce4205548cc794e8225257a96cfe2b6f89030c686aaceb0b7bbc365b0de
emailWorker:
  image:
    repository: acrclustersage.azurecr.io/clustersage/email-worker
    tag: b4766ce
    digest: sha256:63b71653867ff72e61c156fba64456ea1a285ae7973de2feaea6e523e7f09d63
gateway:
  hostname: dev.nexaflow.site
  hostnames:
    - dev.nexaflow.site
migrationJob:
  image:
    repository: acrclustersage.azurecr.io/clustersage/backend
    tag: b4766ce
    digest: sha256:53895ce4205548cc794e8225257a96cfe2b6f89030c686aaceb0b7bbc365b0de
